/**
 * 🚜 ALL TAGS MANIFEST
 * Rules: Lowercase, No spaces (hyphens only), Max 25 chars.
 * This list is used for suggestions in the ReactHashTags component.
 */

const rawTechStack: string[] = [
  // Web Frameworks & UI
  "html",
  "css",
  "javascript",
  "typescript",
  "react",
  "angular",
  "svelte",
  "vue-js",
  "next-js",
  "nuxt-js",
  "bootstrap",
  "tailwind-css",
  "material-ui",
  "chakra-ui",
  "emotion",
  "scss",
  "less",
  "styled-components",
  "jquery",
  "shadcn-ui",
  "daisy-ui",
  "radix-ui",
  "headless-ui",
  "ant-design",
  "mantine",
  "nextui",
  "aceternity-ui",

  // Backend & APIs
  "node-js",
  "express",
  "nestjs",
  "koa",
  "hapi",
  "django",
  "flask",
  "ruby-on-rails",
  "spring-boot",
  "fastapi",
  "laravel",
  "aspnet-core",
  "phoenix-framework",
  "graphql",
  "rest-api",
  "grpc",
  "swagger",
  "postman",

  // Databases & ORMs
  "mongodb",
  "postgresql",
  "mysql",
  "sqlite",
  "mariadb",
  "cassandra",
  "dynamodb",
  "redis",
  "oracle-db",
  "elasticsearch",
  "couchbase",
  "arangodb",
  "clickhouse",
  "timescaledb",
  "prisma",
  "sequelize",
  "typeorm",
  "mikroorm",
  "hibernate",
  "entity-framework",
  "activerecord",
  "doctrine-orm",
  "sqlalchemy",
  "mongoose",
  "drizzle-orm",
  "knex-js",
  "objection-js",
  "hasura",
  "edgedb",
  "supabase-orm",
  "firebase-firestore",

  // Languages
  "python",
  "java",
  "c-sharp",
  "cpp",
  "go",
  "kotlin",
  "swift",
  "rust",
  "php",
  "ruby",
  "perl",
  "scala",
  "r-lang",
  "matlab",
  "dart",
  "solidity",

  // 🚜 Hardware & Low Level (New Additions)
  "verilog",
  "vhdl",
  "fpga",
  "arduino",
  "raspberry-pi",
  "embedded-c",
  "esp32",
  "micro-controller",
  "system-verilog",
  "hdl",
  "assembly",
  "robotics",
  "iot",

  // DevOps & Cloud
  "docker",
  "kubernetes",
  "aws",
  "azure",
  "google-cloud",
  "netlify",
  "vercel",
  "digitalocean",
  "firebase",
  "terraform",
  "ansible",
  "chef",
  "puppet",
  "jenkins",
  "github-actions",
  "circleci",
  "travisci",
  "caprover",
  "rancher",
  "cloudron",
  "portainer",
  "cloudflare-pages",

  // Tools & State Management
  "git",
  "github",
  "gitlab",
  "bitbucket",
  "webpack",
  "parcel",
  "gulp",
  "grunt",
  "rollup",
  "babel",
  "eslint",
  "prettier",
  "storybook",
  "electron",
  "three-js",
  "d3-js",
  "socket-io",
  "figma",
  "adobe-xd",
  "nx",
  "turborepo",
  "redux",
  "mobx",
  "apollo",
  "relay",
  "rxjs",
  "recoil",
  "xstate",
  "zustand",
  "swr",
  "react-query",
  "formik",
  "zod",
  "yup",

  // Testing
  "jest",
  "mocha",
  "chai",
  "cypress",
  "puppeteer",
  "playwright",
  "testing-library",
  "enzyme",
  "selenium",
  "junit",
  "rspec",
  "pytest",
  "vitest",

  // AI & Data Science
  "tensorflow",
  "pytorch",
  "scikit-learn",
  "keras",
  "pandas",
  "numpy",
  "matplotlib",
  "seaborn",
  "opencv",
  "hugging-face",
  "apache-spark",
  "mlflow",
  "chatgpt-api",
  "openai-api",
  "langchain",
  "anthropic-api",

  // Mobile & Game Dev
  "react-native",
  "flutter",
  "ionic",
  "swiftui",
  "xamarin",
  "cordova",
  "unity",
  "unreal-engine",
  "godot",
  "gamemaker",

  // Business, Lifestyle & Finance
  "bitcoin",
  "blockchain",
  "defi",
  "nfts",
  "investing",
  "fintech",
  "stock-market",
  "startups",
  "entrepreneurship",
  "saas",
  "marketing",
  "seo",
  "leadership",
  "productivity",
  "remote-work",
  "bootstrapping",
  "technology",
  "science",
  "future-tech",
  "space",
  "gaming",
  "tutorial",
  "career-advice",
  "ui-design",
  "ux-design",
  "design-systems",
  "framer",
];

// Combine and strictly enforce the unique lowercase slug rule
const uniqueSlugs = [
  ...new Set(rawTechStack.map((tag) => tag.toLowerCase().replace(/\s+/g, "-"))),
];

// Alphabetical sort for a predictable UI
uniqueSlugs.sort((a, b) => a.localeCompare(b));

export const allTags = uniqueSlugs;
